name: mtkp
description: МТКП Space

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.0+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.1
  supabase: ^0.2.10
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  jiffy: ^5.0.0
  tuple: ^2.0.0
  connectivity_plus: ^2.2.0

  json_annotation: ^4.4.0
  url_launcher: ^6.0.18
  flutter_local_notifications: ^9.3.1
  android_alarm_manager_plus: ^2.0.5
  fluttertoast: ^8.0.8
  http: ^0.13.4
  flutter_lints: ^1.0.4
  optimize_battery: ^0.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.1.4

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/full_logo.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"

  flutter_test:
    sdk: flutter

flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/building_plan/building_plan.jpg
